version: '2'
services:
    jenkins_qa:
        build:
            context: docker_conf/.
            dockerfile: Dockerfile
        container_name:  jenkins_qa
        ports:
            - "8080:8080"
        volumes:
            - jenkins_qa_data:/var/jenkins_home/
            - /home/projects/awsb_devops:/var/jenkins_home/awsb_devops
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker:ro
        networks: 
            - jenkins_network

volumes:
    jenkins_qa_data:
        driver: local
        name: jenkins_qa_data
networks:
    jenkins_network:
        name: jenkins_network